using FloorPlanApplication.Data.Enums;
using FloorPlanApplication.Dtos.Service;
using FloorPlanApplication.Extensions;
using FloorPlanApplication.Interfaces;
using FloorPlanApplication.Mappers;
using FloorPlanApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FloorPlanApplication.Controllers
{
    [ApiController]
    [Authorize]
    [Route("api/Services")]
    public class ServiceController : ControllerBase
    {
        private readonly IServiceRepository _serviceRepository;
        private readonly IServiceLogRepository _serviceLogRepository;
        private readonly UserManager<User> _userManager;

        public ServiceController(IServiceRepository serviceRepository, IServiceLogRepository serviceLogRepository, UserManager<User> userManager)
        {
            _serviceRepository = serviceRepository;
            _serviceLogRepository = serviceLogRepository;
            _userManager = userManager;
        }

        [HttpGet]
        [Route("Services")]
        public async Task<IActionResult> GetServicesForUser(int? index)
        {
            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if (user == null)
                return Unauthorized();

            //if admin redirect
            bool isAdmin = await _userManager.IsInRoleAsync(user, UserRole.ADMIN.ToString());

            if (isAdmin)
                return await GetServicesForAdmin(0);

            //if employee redirect
            bool isEmployee = await _userManager.IsInRoleAsync(user, UserRole.EMPLOYEE.ToString());

            if (isEmployee)
                return RedirectToAction(nameof(GetServicesForEmployee), new { index = 0 });

            var servicelist = await _serviceRepository.GetServicesByClientID(user.Id, index ?? 0, 10);

            var services = servicelist.Select(s => s.ToServiceDTO());

            return Ok(services);
        }

        [HttpPost]
        [Route("CreateServiceRequest")]
        public async Task<IActionResult> CreateServiceRequested(CreateServiceDTO DTO)
        {
            if (!ModelState.IsValid || (DTO.OtherServiceTypeName?.Length == 0 && DTO.ServiceType == ServiceType.OTHER))
                return BadRequest(ModelState);

            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if (user == null)
                return Unauthorized();

            bool isAdmin = await _userManager.IsInRoleAsync(user, UserRole.ADMIN.ToString());

            Service newService = DTO.ToServiceFromCreateDTO();

            if (user.ComopanyID != null)
            {
                newService.CompanyID = user.ComopanyID;
            }

            bool ServiceAdded = _serviceRepository.AddService(newService);

            if (ServiceAdded)
            {
                ServiceLog log = new ServiceLog
                {
                    ServiceID = newService.ID,
                    ServiceNotes = $"Service Requested by {user.FirstName} {user.LastName} " +
                                   $"on {newService.ServiceRequestDate.Date} " +
                                   $"at {newService.ServiceRequestDate.TimeOfDay} " +
                                   $", Log generated by automatic agent, awaiting approval",
                    EmployeeID = ""
                };

                bool LogAdded = _serviceLogRepository.AddLog(log);

                if (LogAdded)
                {
                    return Ok(newService);
                }
                else
                {
                    return StatusCode(500);
                }
            }
            else
            {
                return StatusCode(500);
            }
        }

        [HttpPost]
        [Route("AdminUpdateService")]
        public async Task<IActionResult> AdminUpdateService(AdminEditServiceDTO DTO)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if (user == null)
                return Unauthorized();

            var isAdmin = await _userManager.IsInRoleAsync(user, UserRole.ADMIN.ToString());

            if (!isAdmin)
                return Unauthorized();

            var service = await _serviceRepository.GetServiceByID(DTO.ServiceID);

            if (service == null)
                return NotFound();

            var newService = DTO.ToServiceFromAdminEditDTO(service);

            bool isUpdated = _serviceRepository.UpdateService(newService);

            if (!isUpdated)
                return StatusCode(500);

            return RedirectToAction(nameof(GetServiceDetails), new {ID = service.ID});
        }

        [HttpPost]
        [Route("EditService")]
        public async Task<IActionResult> EditService(RegularEditServiceDTO DTO)
        {
            if(!ModelState.IsValid) 
                return BadRequest(ModelState);
        
            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if (user == null)
                return Unauthorized();

            bool isAdmin = await _userManager.IsInRoleAsync(user, UserRole.ADMIN.ToString());
            var service = await _serviceRepository.GetServiceByID(DTO.ServiceID);

            if (service == null)
                return NotFound();

            if (service.ClientID != user.Id && !isAdmin)
                return Unauthorized();

            service.Description = DTO.Description;

            bool isUpdated = _serviceRepository.UpdateService(service);

            if (!isUpdated)
                return StatusCode(500);

            return RedirectToAction(nameof(GetServiceDetails), new { ID = service.ID });
        }

        [HttpGet]
        [Route("ServiceDetails")]
        public async Task<IActionResult> GetServiceDetails([FromRoute] int ID, int? index)
        {
            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if (user == null)
                return Unauthorized();

            bool isAdmin = await _userManager.IsInRoleAsync(user, UserRole.ADMIN.ToString());
            var service = await _serviceRepository.GetServiceByID(ID);

            if (service == null || (service.ClientID != user.Id && !isAdmin))
                return NotFound();

            var logs = await _serviceLogRepository.GetAllLogsByServiceID(ID, index ?? 0, 20);

            service.Logs = logs;    

            return Ok(service);
        }

        [HttpGet]
        private async Task<IActionResult> GetServicesForAdmin(int? index)
        {
            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if (user == null)
                return Unauthorized();

            bool isAdmin = await _userManager.IsInRoleAsync(user, UserRole.ADMIN.ToString());

            if (!isAdmin)
                return Unauthorized();

            var serviceList = await _serviceRepository.GetAllServices(index ?? 0, 20);

            var servies = serviceList.Select(s => s.ToServiceDTO()).ToList();

            return Ok(servies);
        }

        [HttpGet]
        [Route("GetServicesForEmployee")]
        public async Task<IActionResult> GetServicesForEmployee(int? index)
        {
            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if(user == null)
                return Unauthorized();

            bool isAdmin = await _userManager.IsInRoleAsync(user, UserRole.ADMIN.ToString());
            bool isEmployee = false;

            if(!isAdmin)
            {
                isEmployee = await _userManager.IsInRoleAsync(user, UserRole.EMPLOYEE.ToString());
            }

            if(!isEmployee)
                return Unauthorized();
            
            var serviceList = await _serviceRepository.GetServicesByEmployeeID(user.Id, index ?? 0, 20);

            var servies = serviceList.Select(s => s.ToServiceDTO()).ToList();

            return Ok(servies);
        }
    }
}
