using FloorPlanApplication.Data.Enums;
using FloorPlanApplication.Dtos.Service;
using FloorPlanApplication.Extensions;
using FloorPlanApplication.Interfaces;
using FloorPlanApplication.Mappers;
using FloorPlanApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FloorPlanApplication.Controllers
{
    [ApiController]
    [Authorize]
    [Route("api/Services")]
    public class ServiceController : ControllerBase
    {
        private readonly IServiceRepository _serviceRepository;
        private readonly IServiceLogRepository _serviceLogRepository;
        private readonly UserManager<User> _userManager;

        public ServiceController(IServiceRepository serviceRepository, IServiceLogRepository serviceLogRepository, UserManager<User> userManager)
        {
            _serviceRepository = serviceRepository;
            _serviceLogRepository = serviceLogRepository;
            _userManager = userManager;
        }

        [HttpGet]
        [Route("Services")]
        public async Task<IActionResult> GetServicesForUser(int? index)
        {
            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if (user == null)
                return Unauthorized();

            //if admin redirect
            //if employee redirect

            var servicelist = await _serviceRepository.GetServicesByClientID(user.Id, index ?? 0, 10);

            var services = servicelist.Select(s => s.ToServiceDTO());

            return Ok(services);
        }

        [HttpPost]
        [Route("CreateServiceRequest")]
        public async Task<IActionResult> CreateServiceRequested(CreateServiceDTO DTO)
        {
            if(!ModelState.IsValid || (DTO.OtherServiceTypeName?.Length == 0 && DTO.ServiceType == ServiceType.OTHER))
                return BadRequest(ModelState);

            var username = User.GetUsername();

            var user = await _userManager.FindByEmailAsync(username);

            if (user == null)
                return Unauthorized();

            bool isAdmin = await _userManager.IsInRoleAsync(user, UserRole.ADMIN.ToString());
            
            Service newService = DTO.ToServiceFromCreateDTO();
            
            if(user.ComopanyID != null)
            {
                newService.CompanyID = user.ComopanyID;
            }

            bool ServiceAdded = _serviceRepository.AddService(newService);

            if(ServiceAdded)
            {
                ServiceLog log = new ServiceLog
                {
                    ServiceID = newService.ID,
                    ServiceNotes = $"Service Requested by {user.FirstName} {user.LastName} " +
                                   $"on {newService.ServiceRequestDate.Date.ToString()} " +
                                   $"at {newService.ServiceRequestDate.TimeOfDay.ToString()} " +
                                   $", Log generated by default agent, awaiting approval",
                    EmployeeID = ""
                };

                bool LogAdded = _serviceLogRepository.AddLog(log);

                if(LogAdded)
                {
                    return Ok(newService);
                }
                else
                {
                    return StatusCode(500);
                }
            }
            else
            {
                return StatusCode(500);
            }
        }
    }
}
